### ISSUE TITLE
error when trying to stop and start azure vm

### ISSUE THREAD

**Issue by Servh37** [JetBrains/teamcity-azure-agent#105] opened 2018-11-21 02:31 UTC
Hi All,

Hoping some my be able to help we are using this plugin to try and start and stop Azure VM but we are getting the below error and we don't know how to fix the issue.

hope someone can help 

`[2018-11-20 14:04:06,737]   WARN [6 Flush Queue 1] - e.impl.FlushQueueVirtualAction - Failed to start agent. Instance AAE-BAgnt-PRD02 was not found: jetbrains.buildServer.clouds.server.instances.FailedToStartInstanceException: Instance AAE-BAgnt-PRD02 was not found (enable debug to see stacktrace)
[2018-11-20 14:04:07,238]  DEBUG [7 Flush Queue 1] - .server.impl.CloudEventsLogger - BeforeStart instance: profile 'Azure'{id=arm-1, projectId=_Root}, AzureCloudImage{myName='AAE-BAgnt-PRD02'}
[2018-11-20 14:04:07,238]   INFO [7 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure'{id=arm-1, projectId=_Root}, AzureCloudImage{myName='AAE-BAgnt-PRD02'}, hash=qIZQ74EnrU4j2GMlwfNKi1sAuYg2wRYs, reason=Automatic start: Start instance to get instance agent details, CloudInstanceUserData{myAgentName=<none>, myAuthToken='', myServerAddress='https://build.test.it.pickles.com.au', myProfileDescription='Azure BuildAgent Cloud', myIdleTimeout=15 min, myCustomAgentConfigurationParameters={system.cloud.profile_id=arm-1, teamcity.cloud.instance.hash=qIZQ74EnrU4j2GMlwfNKi1sAuYg2wRYs}}
[2018-11-20 14:04:07,238]   WARN [7 Flush Queue 1] - .instances.StartInstanceAction - Failed to start cloud instance: profile 'Azure'{id=arm-1, projectId=_Root}, AzureCloudImage{myName='AAE-BAgnt-PRD02'}. Instance AAE-BAgnt-PRD02 was not found
[2018-11-20 14:04:07,238]  DEBUG [7 Flush Queue 1] - .instances.StartInstanceAction - Failed to start cloud instance: profile 'Azure'{id=arm-1, projectId=_Root}, AzureCloudImage{myName='AAE-BAgnt-PRD02'}. Instance AAE-BAgnt-PRD02 was not found
jetbrains.buildServer.clouds.CloudException: Instance AAE-BAgnt-PRD02 was not found`

**Comment by dtretyakov** [comment] 2018-11-21 11:58
@Servh37, could you please ensure that the vm with name `AAE-BAgnt-PRD02` is actually exists in your Azure account and TeamCity displays it under Agents -> Cloud page in the stopped state?

**Comment by dtretyakov** [comment] 2018-11-21 15:48
There is the similar problem, looks like regression in cloud image parameters configuration: https://youtrack.jetbrains.com/issue/TW-57928

**Comment by Servh37** [comment] 2018-11-22 00:05
Hi @dtretyakov, yes the VM does exists in Azure it is our current build VM. 

that where just try to shut down and start up on demand.

Agents -> Cloud page in the stopped state? Yes it is in the stopped state and when we click on Start it provides that error in the logs.

**Comment by dtretyakov** [comment] 2018-11-22 17:09
@Servh37, the problem was addressed in the plugin version 0.8.8: https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support
Please try updating and check whether it solves it in your case.

**Closed** 2018-11-22 17:09 UTC
Labels: bug, regression

**Comment by Servh37** [comment] 2018-11-22 21:59
Thank you @dtretyakov i will update the plugging and let you know the outcome.

**Comment by Servh37** [comment] 2018-11-26 00:17
Hi @dtretyakov, i can confirm the fixes you have need in version 0.88 has fix the issue.

I have testing this and now working as it should.
